"""
app/report_formatting.py — plain-text report formatting for the three
evaluation phases (retrieval eval, RAGAS, citation verification).

Shared by app.py (Gradio) and streamlit_app.py so both UIs render the
identical report for the identical underlying result, instead of each
maintaining its own formatting that can drift out of sync.
"""

_SEP = "-" * 56


def format_retrieval_eval(result: dict, doc_name: str) -> str:
    """Phase 1 — formats the output of QAChainWrapper.run_retrieval_eval()."""
    if "error" in result:
        return f"Evaluation error: {result['error']}"

    k = result.get("k")
    n = result.get("n_questions", 0)
    _INTERPRET = {
        "precision_at_k": f"of {k} retrieved chunks, how many contained the answer",
        "recall_at_k":    f"was the source chunk found anywhere in top {k}?",
        "mrr":            "1/rank of first relevant result — higher = answer ranked earlier",
        "coverage":       "% of questions where at least 1 relevant chunk was found",
    }
    lines = [
        f"Phase 1 — Retrieval Evaluation  ({n} synthetic questions, K={k})",
        _SEP,
        f"Document: {doc_name}",
        _SEP,
    ]
    for key in ["precision_at_k", "recall_at_k", "mrr", "coverage"]:
        score = result.get(key, 0.0)
        bar = "#" * int(score * 20)
        label = key.replace("_", " ").replace("at k", f"@{k}").title().ljust(18)
        lines.append(f"{label}  {score:.3f}  [{bar:<20}]  {_INTERPRET[key]}")
    lines += [
        _SEP,
        "Score: 0.0 = poor   0.5 = acceptable   1.0 = perfect",
        "Synthetic test set — questions auto-generated by LLM from document chunks.",
    ]
    return "\n".join(lines)


def format_ragas_eval(scores: dict, question: str) -> str:
    """Phase 2 — formats the output of evaluate_rag_response()."""
    if "info" in scores:
        return scores["info"]
    if "error" in scores:
        return f"Evaluation error: {scores['error']}"

    _LABELS = {
        "faithfulness": "Faithfulness        ",
        "answer_relevancy": "Answer Relevancy    ",
        "context_precision": "Context Precision   ",
        "llm_context_precision_without_reference": "Context Precision   ",
    }
    _INTERPRET = {
        "faithfulness": "answer is grounded in source chunks (hallucination check)",
        "answer_relevancy": "answer addresses the question asked",
        "context_precision": "retrieved chunks are relevant to the query",
        "llm_context_precision_without_reference": "retrieved chunks are relevant to the query",
    }

    lines = [
        "RAGAS Evaluation  (LLM-judged via Groq)",
        _SEP,
        f"Question: {question[:80]}{'...' if len(question) > 80 else ''}",
        _SEP,
    ]
    for key, score in scores.items():
        label = _LABELS.get(key, key.ljust(20))
        interp = _INTERPRET.get(key, "")
        bar = "#" * int(score * 20)
        lines.append(f"{label}  {score:.3f}  [{bar:<20}]  {interp}")

    lines += [_SEP, "Score: 0.0 = poor   0.5 = acceptable   1.0 = perfect"]
    return "\n".join(lines)


def format_citation_verification(result: dict, question: str) -> str:
    """Phase 4 — formats the output of verify_citations()."""
    citations = result["citations"]
    uncited = result["uncited_sentences"]

    lines = [
        "Citation Verification  (LLM-judged, one call per cited sentence)",
        _SEP,
        f"Question: {question[:80]}{'...' if len(question) > 80 else ''}",
        _SEP,
    ]

    cov_bar = "#" * int(result["coverage"] * 20)
    acc_bar = "#" * int(result["accuracy"] * 20)
    lines.append(f"Coverage   {result['coverage']:.3f}  [{cov_bar:<20}]  claims with a citation attached")
    lines.append(f"Accuracy   {result['accuracy']:.3f}  [{acc_bar:<20}]  citations actually supported by their source")

    unsupported = [c for c in citations if not c["supported"]]
    if unsupported:
        lines += [_SEP, f"UNSUPPORTED CITATIONS ({len(unsupported)}):"]
        for c in unsupported[:5]:
            src = ", ".join(str(n) for n in c["cited_sources"])
            lines.append(f"  [{src}] \"{c['sentence'][:100]}\"")
            lines.append(f"        -> {c['reason']}")
        if len(unsupported) > 5:
            lines.append(f"  ... and {len(unsupported) - 5} more")
    elif citations:
        lines += [_SEP, "All cited claims were supported by their source chunk."]

    if uncited:
        lines += [_SEP, f"UNCITED CLAIMS ({len(uncited)}) — stated without a source number:"]
        for s in uncited[:5]:
            lines.append(f"  \"{s[:100]}\"")

    lines += [_SEP, "0.0 = poor   1.0 = perfect"]
    return "\n".join(lines)
