"""
app/report_formatting.py — plain-text report formatting for the three
evaluation phases (retrieval eval, RAGAS, citation verification), plus HTML
fragments for the answer card, confidence/category bars, source detail, and
hybrid-vs-dense-only comparison.

Shared by app.py (Gradio) and streamlit_app.py so both UIs render the
identical output for the identical underlying result, instead of each
maintaining its own formatting/markup that can drift out of sync.
"""

import html
import re

_SEP = "-" * 56


def format_retrieval_eval(result: dict, doc_name: str) -> str:
    """Phase 1 — formats the output of QAChainWrapper.run_retrieval_eval()."""
    if "error" in result:
        return f"Evaluation error: {result['error']}"

    k = result.get("k")
    n = result.get("n_questions", 0)
    _INTERPRET = {
        "precision_at_k": f"of {k} retrieved chunks, how many contained the answer",
        "recall_at_k":    f"was the source chunk found anywhere in top {k}?",
        "mrr":            "1/rank of first relevant result — higher = answer ranked earlier",
        "coverage":       "% of questions where at least 1 relevant chunk was found",
    }
    lines = [
        f"Phase 1 — Retrieval Evaluation  ({n} synthetic questions, K={k})",
        _SEP,
        f"Document: {doc_name}",
        _SEP,
    ]
    for key in ["precision_at_k", "recall_at_k", "mrr", "coverage"]:
        score = result.get(key, 0.0)
        bar = "#" * int(score * 20)
        label = key.replace("_", " ").replace("at k", f"@{k}").title().ljust(18)
        lines.append(f"{label}  {score:.3f}  [{bar:<20}]  {_INTERPRET[key]}")
    lines += [
        _SEP,
        "Score: 0.0 = poor   0.5 = acceptable   1.0 = perfect",
        "Synthetic test set — questions auto-generated by LLM from document chunks.",
    ]
    return "\n".join(lines)


def format_ragas_eval(scores: dict, question: str) -> str:
    """Phase 2 — formats the output of evaluate_rag_response()."""
    if "info" in scores:
        return scores["info"]
    if "error" in scores:
        return f"Evaluation error: {scores['error']}"

    _LABELS = {
        "faithfulness": "Faithfulness        ",
        "answer_relevancy": "Answer Relevancy    ",
        "context_precision": "Context Precision   ",
        "llm_context_precision_without_reference": "Context Precision   ",
    }
    _INTERPRET = {
        "faithfulness": "answer is grounded in source chunks (hallucination check)",
        "answer_relevancy": "answer addresses the question asked",
        "context_precision": "retrieved chunks are relevant to the query",
        "llm_context_precision_without_reference": "retrieved chunks are relevant to the query",
    }

    lines = [
        "RAGAS Evaluation  (LLM-judged via Groq)",
        _SEP,
        f"Question: {question[:80]}{'...' if len(question) > 80 else ''}",
        _SEP,
    ]
    for key, score in scores.items():
        label = _LABELS.get(key, key.ljust(20))
        interp = _INTERPRET.get(key, "")
        bar = "#" * int(score * 20)
        lines.append(f"{label}  {score:.3f}  [{bar:<20}]  {interp}")

    lines += [_SEP, "Score: 0.0 = poor   0.5 = acceptable   1.0 = perfect"]
    return "\n".join(lines)


def format_citation_verification(result: dict, question: str) -> str:
    """Phase 4 — formats the output of verify_citations()."""
    citations = result["citations"]
    uncited = result["uncited_sentences"]

    lines = [
        "Citation Verification  (LLM-judged, one call per cited sentence)",
        _SEP,
        f"Question: {question[:80]}{'...' if len(question) > 80 else ''}",
        _SEP,
    ]

    cov_bar = "#" * int(result["coverage"] * 20)
    acc_bar = "#" * int(result["accuracy"] * 20)
    lines.append(f"Coverage   {result['coverage']:.3f}  [{cov_bar:<20}]  claims with a citation attached")
    lines.append(f"Accuracy   {result['accuracy']:.3f}  [{acc_bar:<20}]  citations actually supported by their source")

    unsupported = [c for c in citations if not c["supported"]]
    if unsupported:
        lines += [_SEP, f"UNSUPPORTED CITATIONS ({len(unsupported)}):"]
        for c in unsupported[:5]:
            src = ", ".join(str(n) for n in c["cited_sources"])
            lines.append(f"  [{src}] \"{c['sentence'][:100]}\"")
            lines.append(f"        -> {c['reason']}")
        if len(unsupported) > 5:
            lines.append(f"  ... and {len(unsupported) - 5} more")
    elif citations:
        lines += [_SEP, "All cited claims were supported by their source chunk."]

    if uncited:
        lines += [_SEP, f"UNCITED CLAIMS ({len(uncited)}) — stated without a source number:"]
        for s in uncited[:5]:
            lines.append(f"  \"{s[:100]}\"")

    lines += [_SEP, "0.0 = poor   1.0 = perfect"]
    return "\n".join(lines)


# =============================================================================
# HTML fragments — answer card, bars, source detail, comparison panels
# =============================================================================
_SUPERSCRIPT_RUN = re.compile(r"[⁰¹²³⁴-⁹]+")


def format_answer_html(text: str) -> str:
    """Escapes the answer text, highlights citation superscripts (¹²³) as
    styled '.cite' spans, and sets off an "Analogy:" line (if present) with
    the '.analogy' class -- same convention the prompt uses
    (rag_pipeline.py:_QUERY_PROMPTS). Caller wraps the result in a
    '.answer-card' container."""
    paragraphs = []
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        escaped = html.escape(line)
        escaped = _SUPERSCRIPT_RUN.sub(lambda m: f'<span class="cite">{m.group(0)}</span>', escaped)
        if line.startswith("Analogy:"):
            paragraphs.append(f'<span class="analogy">{escaped}</span>')
        else:
            paragraphs.append(f"<p>{escaped}</p>")
    return "\n".join(paragraphs)


def format_bar_html(label: str, value_str: str, pct: float) -> str:
    """One labeled progress bar -- used for both the confidence breakdown
    and the golden-eval per-category scorecard.

    Each span sets its own `color ... !important` rather than relying on
    inheriting it from the parent div's color -- Gradio ships a universal
    `.gradio-container * { color: ... !important }` reset that beats a
    plain inherited value even though it doesn't beat an element's own
    `!important` (same class of bug as the invisible tab-label fix)."""
    pct = min(max(pct, 0.0), 1.0)
    return f"""
    <div style="margin-bottom:14px;">
      <div style="display:flex; justify-content:space-between; font-size:0.88em; margin-bottom:4px;">
        <span style="font-weight:600; text-transform:capitalize; color:#5A3010 !important;">{html.escape(label)}</span>
        <span style="color:#5A3010 !important;">{html.escape(value_str)}</span>
      </div>
      <div style="background:#FFE3CC; border-radius:8px; height:10px; overflow:hidden;">
        <div style="width:{pct * 100:.1f}%; height:100%; background:linear-gradient(90deg,#DBB06B,#E39A7B); border-radius:8px;"></div>
      </div>
    </div>
    """


def _snippet_key(text: str) -> str:
    return text[:80]


def format_source_detail_html(source: dict) -> str:
    """The '.meta-line' + '.snippet' block for one selected source chunk."""
    content = html.escape(source.get("full_content", source.get("content", "")))
    return (
        f'<div class="meta-line">SOURCE {source.get("chunk")} &middot; PAGE {source.get("page", "N/A")} '
        f'&middot; RERANK SCORE {source.get("score", "N/A")}</div>'
        f'<div class="snippet">{content}</div>'
    )


def format_comparison_html(hybrid_sources: list, dense_docs: list) -> tuple:
    """Returns (hybrid_html, dense_html) -- the two side-by-side retrieval
    comparison panels. dense_docs are langchain Document objects, as
    returned by rag_pipeline.dense_only_retrieve()."""
    hybrid_keys = {_snippet_key(s.get("full_content", s.get("content", ""))) for s in hybrid_sources}
    dense_keys = {_snippet_key(d.metadata.get("original_content", d.page_content)) for d in dense_docs}

    hybrid_parts = []
    for s in hybrid_sources:
        content = s.get("full_content", s.get("content", ""))
        overlap = " &middot; ALSO IN DENSE-ONLY" if _snippet_key(content) in dense_keys else ""
        hybrid_parts.append(
            f'<div class="meta-line">PAGE {s.get("page", "N/A")} &middot; SCORE {s.get("score", "N/A")}{overlap}</div>'
            f'<div class="snippet">{html.escape(content[:220])}</div><div style="height:12px"></div>'
        )

    dense_parts = []
    for d in dense_docs:
        content = d.metadata.get("original_content", d.page_content)
        overlap = " &middot; ALSO IN HYBRID" if _snippet_key(content) in hybrid_keys else ""
        dense_parts.append(
            f'<div class="meta-line">PAGE {d.metadata.get("page", "N/A")} &middot; SCORE {d.metadata.get("rerank_score", "N/A")}{overlap}</div>'
            f'<div class="snippet">{html.escape(content[:220])}</div><div style="height:12px"></div>'
        )

    return "".join(hybrid_parts), "".join(dense_parts)
